### ISSUE TITLE
【笔记】css3中的函数和“事件”

### ISSUE THREAD

**Issue by holylovelqq** [holylovelqq/develop#2]
1. 目前css中可用的函数有：
- attr()-----css2开始出现，使用率不高
- calc()-----css3增加，**非常实用**
- linear-gradient()/radial-gradient()/repeating-linear-gradient()/repeating-radial-gradient()----生成线性渐变背景色图像，需要的情况下会用到，整体使用率不是很高

例子：
``` css
.content {
  /* 除了按钮以外的宽度4等分 */
  width: calc((100% - 120px) / 4);
  height: 40px;
  max-width: 350px;
}
```

2. 所谓的“事件”，并不是真的事件，只是控制元素能否成为鼠标时间的目标。这里讲的是pointer-events:auto|none
- pointer-events:none;时元素永远不会成为鼠标事件的target。但是，当其后代元素的pointer-events属性指定其他值时，鼠标事件可以指向后代元素，在这种情况下，鼠标事件将在捕获或冒泡阶触发父元素的事件侦听器。
- pointer-events:auto;默认值

例子：
``` css
.cofirm {
  pointer-events: none;
  background-color: #fff;
  opacity: 0;
}

.confirm.active {
  pointer-events: auto;
  opacity: 0.8;
}
```

参考：[css函数](https://www.html.cn/book/css/values/functional/calc%28%29.htm)和[css3用户界面](https://www.html.cn/book/css/properties/user-interface/pointer-events.htm)

更多其他介绍参见上面的参考链接
